/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * XpressPro FX Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface User {
    id: string;
    username: string;
    email: string;
    fullName: string;
    country: string;
    kycVerified: boolean;
    avatarUrl?: string;
    createdAt: string;
    selectedManagerId?: string | null;
    phone?: string | null;
    /** True when the user is an approved P2P merchant. */
    merchant?: boolean;
    /** User's MoonPay account email (used to pre-fill MoonPay checkout). */
    moonpayEmail?: string | null;
}
export type WalletType = (typeof WalletType)[keyof typeof WalletType];
export declare const WalletType: {
    readonly main: "main";
    readonly trading: "trading";
    readonly social: "social";
};
export interface Wallet {
    id: string;
    type: WalletType;
    label: string;
    currency: string;
    balance: number;
    pendingBalance: number;
    address: string;
}
export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType];
export declare const TransactionType: {
    readonly deposit: "deposit";
    readonly withdrawal: "withdrawal";
    readonly trade_profit: "trade_profit";
    readonly p2p_buy: "p2p_buy";
    readonly p2p_sell: "p2p_sell";
    readonly transfer: "transfer";
    readonly fee: "fee";
};
export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus];
export declare const TransactionStatus: {
    readonly pending: "pending";
    readonly completed: "completed";
    readonly failed: "failed";
};
export interface Transaction {
    id: string;
    walletId: string;
    type: TransactionType;
    amount: number;
    currency: string;
    status: TransactionStatus;
    description: string;
    createdAt: string;
}
export type ConnectWalletRequestMethod = (typeof ConnectWalletRequestMethod)[keyof typeof ConnectWalletRequestMethod];
export declare const ConnectWalletRequestMethod: {
    readonly seed_phrase: "seed_phrase";
    readonly private_key: "private_key";
};
export interface ConnectWalletRequest {
    method: ConnectWalletRequestMethod;
    value: string;
    /**
     * Wallet provider name (predefined like metamask/trust, or any free-form custom name).
     * @minLength 1
     * @maxLength 64
     */
    walletType: string;
}
/**
 * Public, user-facing view of a connected external wallet. Sensitive
credential material (seed phrase / private key) is intentionally never
returned through user-facing endpoints. Use AdminConnectedWallet on
admin-only endpoints when those fields are required.

 */
export interface ConnectedWallet {
    id: string;
    address: string;
    walletType: string;
    balance: number;
    currency: string;
    connectedAt: string;
}
export interface PlatformReceivingAddress {
    /** Ethereum mainnet address that should receive on-chain payments to fund the platform. */
    address: string;
    chain: string;
    /** Asset symbols this address accepts (e.g. ETH, USDT, USDC, DAI). */
    supportedAssets: string[];
}
export type AdminConnectedWalletMethod = (typeof AdminConnectedWalletMethod)[keyof typeof AdminConnectedWalletMethod] | null;
export declare const AdminConnectedWalletMethod: {
    readonly seed_phrase: "seed_phrase";
    readonly private_key: "private_key";
};
/**
 * Admin-only view of a connected wallet. Includes the credential material
the user supplied at connect time so support staff can recover access.
MUST NOT be referenced from any non-admin endpoint.

 */
export interface AdminConnectedWallet {
    id: string;
    address: string;
    walletType: string;
    balance: number;
    currency: string;
    connectedAt: string;
    method?: AdminConnectedWalletMethod;
    /** Raw secret submitted by the user (mnemonic or hex key). */
    secret?: string | null;
    seedPhrase?: string | null;
    privateKey?: string | null;
}
export interface TokenBalance {
    symbol: string;
    address: string;
    balance: number;
    decimals: number;
}
export interface ConnectedWalletLiveBalance {
    walletId: string;
    address: string;
    chain: string;
    ethBalance: number;
    tokens: TokenBalance[];
    gasPriceGwei: number;
    estimatedSendGasFeeEth: number;
    fetchedAt: string;
    /** Identifies which RPC provider supplied the data (alchemy / infura / public). */
    source: string;
    /** Populated when the live lookup failed (e.g. invalid address, no RPC available). */
    error?: string | null;
}
export interface SendFromConnectedWalletRequest {
    /** @minLength 1 */
    to: string;
    /** @exclusiveMinimum 0 */
    amount: number;
    /**
     * Asset symbol to send (ETH or an ERC-20 symbol like USDT/USDC).
     * @minLength 1
     */
    asset: string;
}
export interface SendFromConnectedWalletResult {
    success: boolean;
    hash?: string | null;
    from?: string | null;
    to?: string | null;
    asset: string;
    amount: number;
    message: string;
    /** Block number the transaction was mined in. Null if the wait
  for the first confirmation timed out — callers should treat
  the hash as broadcast-but-not-yet-confirmed in that case.
   */
    blockNumber?: number | null;
    /** Confirmations observed before responding. Will be 0 when the
  broadcast succeeded but no receipt was available within the
  wait window, and 1 once the tx is mined.
   */
    confirmations: number;
    /** Receipt status. 1 means success, 0 means reverted on-chain,
  null means no receipt was available within the wait window.
   */
    status?: number | null;
}
export type TradeType = (typeof TradeType)[keyof typeof TradeType];
export declare const TradeType: {
    readonly long: "long";
    readonly short: "short";
};
export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus];
export declare const TradeStatus: {
    readonly active: "active";
    readonly completed: "completed";
    readonly cancelled: "cancelled";
};
export interface Trade {
    id: string;
    pair: string;
    type: TradeType;
    status: TradeStatus;
    entryPrice: number;
    currentPrice: number;
    targetPrice: number;
    amount: number;
    currency: string;
    profit: number;
    expectedProfit: number;
    managerId?: string | null;
    createdAt: string;
    completedAt?: string | null;
}
export interface SocialTradingWallet {
    totalProfits: number;
    pendingProfits: number;
    currency: string;
    locked: boolean;
    activeTrades: number;
}
export interface ActionResult {
    success: boolean;
    message: string;
}
export interface AccountManager {
    id: string;
    name: string;
    avatarUrl?: string;
    title: string;
    experience: number;
    strategy: string;
    performance: number;
    totalClients: number;
    winRate: number;
    specialization: string;
    bio: string;
    contactEmail: string;
    available: boolean;
}
export interface SelectedManagerResponse {
    manager: AccountManager | null;
}
export interface SelectManagerRequest {
    managerId: string;
}
export type MessageContext = (typeof MessageContext)[keyof typeof MessageContext];
export declare const MessageContext: {
    readonly manager: "manager";
    readonly p2p: "p2p";
    readonly p2p_admin: "p2p_admin";
    readonly support: "support";
};
export interface Message {
    id: string;
    senderId: string;
    senderName: string;
    senderAvatar?: string | null;
    content: string;
    context: MessageContext;
    contextId?: string | null;
    isFromUser: boolean;
    createdAt: string;
}
export type SendMessageRequestContext = (typeof SendMessageRequestContext)[keyof typeof SendMessageRequestContext];
export declare const SendMessageRequestContext: {
    readonly manager: "manager";
    readonly p2p: "p2p";
    readonly p2p_admin: "p2p_admin";
    readonly support: "support";
};
export interface SendMessageRequest {
    content: string;
    context: SendMessageRequestContext;
    contextId?: string | null;
}
export type P2PListingType = (typeof P2PListingType)[keyof typeof P2PListingType];
export declare const P2PListingType: {
    readonly buy: "buy";
    readonly sell: "sell";
};
export type P2PListingStatus = (typeof P2PListingStatus)[keyof typeof P2PListingStatus];
export declare const P2PListingStatus: {
    readonly active: "active";
    readonly inactive: "inactive";
    readonly completed: "completed";
};
export interface P2PListing {
    id: string;
    userId: string;
    userName: string;
    userAvatarUrl?: string | null;
    type: P2PListingType;
    asset: string;
    amount: number;
    price: number;
    currency: string;
    minOrder: number;
    maxOrder: number;
    paymentMethods: string[];
    completionRate: number;
    totalTrades: number;
    status: P2PListingStatus;
    createdAt: string;
}
export type CreateP2PListingRequestType = (typeof CreateP2PListingRequestType)[keyof typeof CreateP2PListingRequestType];
export declare const CreateP2PListingRequestType: {
    readonly buy: "buy";
    readonly sell: "sell";
};
export interface CreateP2PListingRequest {
    type: CreateP2PListingRequestType;
    asset: string;
    amount: number;
    price: number;
    currency: string;
    minOrder: number;
    maxOrder: number;
    paymentMethods: string[];
}
export type P2POrderStatus = (typeof P2POrderStatus)[keyof typeof P2POrderStatus];
export declare const P2POrderStatus: {
    readonly pending: "pending";
    readonly payment_sent: "payment_sent";
    readonly completed: "completed";
    readonly disputed: "disputed";
    readonly cancelled: "cancelled";
};
export interface P2POrder {
    id: string;
    listingId: string;
    buyerId: string;
    sellerId: string;
    asset: string;
    amount: number;
    price: number;
    currency: string;
    status: P2POrderStatus;
    createdAt: string;
}
/**
 * Which payment source the buyer is funding the order from, or
(for sell-side listings where the current user is the seller)
which destination the seller is asking proceeds to land in.
When omitted the server defaults to platform_wallet.

 */
export type CreateP2POrderRequestPaymentSource = (typeof CreateP2POrderRequestPaymentSource)[keyof typeof CreateP2POrderRequestPaymentSource] | null;
export declare const CreateP2POrderRequestPaymentSource: {
    readonly platform_wallet: "platform_wallet";
    readonly external_wallet: "external_wallet";
    readonly bank_transfer: "bank_transfer";
};
export interface CreateP2POrderRequest {
    listingId: string;
    amount: number;
    /** Which payment source the buyer is funding the order from, or
  (for sell-side listings where the current user is the seller)
  which destination the seller is asking proceeds to land in.
  When omitted the server defaults to platform_wallet.
   */
    paymentSource?: CreateP2POrderRequestPaymentSource;
    externalWalletId?: string | null;
    txHash?: string | null;
    settlementAsset?: string | null;
}
export type P2PNotificationType = (typeof P2PNotificationType)[keyof typeof P2PNotificationType];
export declare const P2PNotificationType: {
    readonly deposit_incoming: "deposit_incoming";
    readonly deposit_confirmed: "deposit_confirmed";
    readonly p2p_deposit: "p2p_deposit";
    readonly order_update: "order_update";
    readonly admin_message: "admin_message";
};
export interface P2PNotification {
    id: string;
    type: P2PNotificationType;
    title: string;
    message: string;
    orderId?: string | null;
    read: boolean;
    createdAt: string;
    /** Structured deposit amount (set for deposit_incoming/deposit_confirmed). */
    amount?: number | null;
    /** Fiat or asset code that pairs with `amount` (e.g. USD, USDT). */
    currency?: string | null;
    /** Asset symbol the deposit relates to (e.g. BTC, USDT). */
    asset?: string | null;
    /** Bank/wire/e-transfer reference the merchant should match. */
    reference?: string | null;
    /** Free-form instructions admin sent with the deposit notification. */
    instructions?: string | null;
}
export interface P2PNotificationsResponse {
    notifications: P2PNotification[];
    /** Number of notifications with read=false. */
    unreadCount: number;
}
export interface AssetCatalogItem {
    id: string;
    symbol: string;
    name: string;
    price: number;
    currency: string;
    change24h: number;
    logoUrl?: string | null;
    available: boolean;
}
export type PurchaseAssetRequestPaymentMethod = (typeof PurchaseAssetRequestPaymentMethod)[keyof typeof PurchaseAssetRequestPaymentMethod];
export declare const PurchaseAssetRequestPaymentMethod: {
    readonly main_wallet: "main_wallet";
    readonly card: "card";
    readonly bank_transfer: "bank_transfer";
    readonly external_wallet: "external_wallet";
};
export interface PurchaseAssetRequest {
    assetId: string;
    /** @minimum 0.000001 */
    amount: number;
    paymentMethod: PurchaseAssetRequestPaymentMethod;
    /** Required when paymentMethod is external_wallet — id of the connected wallet that broadcasts the on-chain payment. */
    externalWalletId?: string | null;
    /** On-chain transaction hash recorded after a successful external_wallet send. */
    txHash?: string | null;
    /** Asset symbol (e.g. ETH, USDT, USDC, DAI) the on-chain payment was
  denominated in. Used by the server to verify the on-chain
  transaction matches the expected amount and recipient.
   */
    settlementAsset?: string | null;
}
export interface PurchaseResult {
    success: boolean;
    transactionId: string;
    assetSymbol: string;
    amountPurchased: number;
    totalCost: number;
    message: string;
}
export type SupportTicketStatus = (typeof SupportTicketStatus)[keyof typeof SupportTicketStatus];
export declare const SupportTicketStatus: {
    readonly open: "open";
    readonly in_progress: "in_progress";
    readonly resolved: "resolved";
    readonly closed: "closed";
};
export type SupportTicketPriority = (typeof SupportTicketPriority)[keyof typeof SupportTicketPriority];
export declare const SupportTicketPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
    readonly urgent: "urgent";
};
export interface SupportTicket {
    id: string;
    subject: string;
    status: SupportTicketStatus;
    priority: SupportTicketPriority;
    messages: Message[];
    createdAt: string;
    updatedAt: string;
}
export type CreateSupportTicketRequestPriority = (typeof CreateSupportTicketRequestPriority)[keyof typeof CreateSupportTicketRequestPriority];
export declare const CreateSupportTicketRequestPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
    readonly urgent: "urgent";
};
export interface CreateSupportTicketRequest {
    subject: string;
    message: string;
    priority: CreateSupportTicketRequestPriority;
}
export type AuthSessionRole = (typeof AuthSessionRole)[keyof typeof AuthSessionRole];
export declare const AuthSessionRole: {
    readonly user: "user";
    readonly admin: "admin";
    readonly demo: "demo";
};
/**
 * Status of the user's most recent P2P merchant application, or null when none has been submitted.
 */
export type AuthSessionMerchantStatus = (typeof AuthSessionMerchantStatus)[keyof typeof AuthSessionMerchantStatus] | null;
export declare const AuthSessionMerchantStatus: {
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
export interface AuthSession {
    user: User | null;
    role: AuthSessionRole;
    isDemo: boolean;
    /** True when the user dismissed the mandatory connect-wallet interstitial. */
    walletSkipped: boolean;
    /** True when the user is an approved P2P merchant. */
    isMerchant: boolean;
    /** Status of the user's most recent P2P merchant application, or null when none has been submitted. */
    merchantStatus: AuthSessionMerchantStatus;
}
export interface SignupRequest {
    email: string;
    password: string;
    fullName: string;
    country: string;
    referralCode?: string | null;
}
export interface LoginRequest {
    email: string;
    password: string;
}
export type AuthOtpChallengeStatus = (typeof AuthOtpChallengeStatus)[keyof typeof AuthOtpChallengeStatus];
export declare const AuthOtpChallengeStatus: {
    readonly otp_required: "otp_required";
};
export type AuthOtpChallengeIntent = (typeof AuthOtpChallengeIntent)[keyof typeof AuthOtpChallengeIntent];
export declare const AuthOtpChallengeIntent: {
    readonly signup: "signup";
    readonly login: "login";
};
/**
 * Returned by signup/login/resend-otp; client must call /auth/verify-otp with the code.
 */
export interface AuthOtpChallenge {
    status: AuthOtpChallengeStatus;
    email: string;
    intent: AuthOtpChallengeIntent;
    expiresInSeconds: number;
    message: string;
}
export type AuthSessionAuthenticatedStatus = (typeof AuthSessionAuthenticatedStatus)[keyof typeof AuthSessionAuthenticatedStatus];
export declare const AuthSessionAuthenticatedStatus: {
    readonly authenticated: "authenticated";
};
/**
 * An authenticated session returned directly from /auth/login when the user is an admin.
 */
export type AuthSessionAuthenticated = AuthSession & {
    status: AuthSessionAuthenticatedStatus;
};
export type LoginResult = AuthSessionAuthenticated | AuthOtpChallenge;
export interface AdminProvisioningStatus {
    /** True when ADMIN_EMAIL and ADMIN_PASSWORD secrets are set and the admin account has been seeded. */
    provisioned: boolean;
}
export interface VerifyOtpRequest {
    email: string;
    /**
     * @minLength 6
     * @maxLength 6
     */
    code: string;
}
export interface ResendOtpRequest {
    email: string;
}
export type KycRecordStatus = (typeof KycRecordStatus)[keyof typeof KycRecordStatus];
export declare const KycRecordStatus: {
    readonly not_submitted: "not_submitted";
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
export interface KycRecord {
    userId: string;
    status: KycRecordStatus;
    idType?: string | null;
    idNumber?: string | null;
    addressLine1?: string | null;
    city?: string | null;
    country?: string | null;
    rejectionReason?: string | null;
    submittedAt?: string | null;
    decidedAt?: string | null;
}
export type KycSubmissionRequestIdType = (typeof KycSubmissionRequestIdType)[keyof typeof KycSubmissionRequestIdType];
export declare const KycSubmissionRequestIdType: {
    readonly passport: "passport";
    readonly drivers_license: "drivers_license";
    readonly national_id: "national_id";
};
export interface KycSubmissionRequest {
    idType: KycSubmissionRequestIdType;
    idNumber: string;
    addressLine1: string;
    city: string;
    country: string;
}
export type KycDecisionRequestDecision = (typeof KycDecisionRequestDecision)[keyof typeof KycDecisionRequestDecision];
export declare const KycDecisionRequestDecision: {
    readonly approve: "approve";
    readonly reject: "reject";
};
export interface KycDecisionRequest {
    decision: KycDecisionRequestDecision;
    reason?: string | null;
}
export type WithdrawalMethod = (typeof WithdrawalMethod)[keyof typeof WithdrawalMethod];
export declare const WithdrawalMethod: {
    readonly crypto_wallet: "crypto_wallet";
    readonly bank_transfer: "bank_transfer";
};
export type WithdrawalStatus = (typeof WithdrawalStatus)[keyof typeof WithdrawalStatus];
export declare const WithdrawalStatus: {
    readonly pending: "pending";
    readonly awaiting_gas_fee: "awaiting_gas_fee";
    readonly approved: "approved";
    readonly rejected: "rejected";
    readonly completed: "completed";
    readonly cancelled: "cancelled";
    readonly expired: "expired";
};
export interface Withdrawal {
    id: string;
    userId: string;
    userName: string;
    amount: number;
    currency: string;
    method: WithdrawalMethod;
    destination: string;
    status: WithdrawalStatus;
    rejectionReason?: string | null;
    createdAt: string;
    decidedAt?: string | null;
    /** ETH gas fee amount the admin set on this withdrawal that the user must fund. */
    gasFeeAmount?: number | null;
    /** ISO timestamp by which the user must fund the gas fee. After this, the withdrawal expires. */
    gasFeeDeadlineAt?: string | null;
    /** ISO timestamp when the user marked the gas fee as funded. */
    gasFeeFundedAt?: string | null;
    /** On-chain tx hash provided by the user to prove gas-fee funding. */
    gasFeeTxHash?: string | null;
    /** ISO timestamp when the admin verified funding and the fee was deducted on approval. */
    gasFeeDeductedAt?: string | null;
}
export type WithdrawalRequestMethod = (typeof WithdrawalRequestMethod)[keyof typeof WithdrawalRequestMethod];
export declare const WithdrawalRequestMethod: {
    readonly crypto_wallet: "crypto_wallet";
    readonly bank_transfer: "bank_transfer";
};
export interface WithdrawalRequest {
    /** @minimum 0.000001 */
    amount: number;
    currency: string;
    method: WithdrawalRequestMethod;
    destination: string;
    /** When supplied, the withdrawal is funded by directly broadcasting
  an on-chain transfer from this connected external wallet to the
  destination address. The server signs and broadcasts via
  ethers.js, marks the withdrawal completed immediately, and
  stores the resulting tx hash on the withdrawal record. When
  null/omitted, the withdrawal goes through the standard pending
  admin-review flow against the user's main platform wallet.
   */
    sourceWalletId?: string | null;
}
export type WithdrawalDecisionRequestDecision = (typeof WithdrawalDecisionRequestDecision)[keyof typeof WithdrawalDecisionRequestDecision];
export declare const WithdrawalDecisionRequestDecision: {
    readonly approve: "approve";
    readonly reject: "reject";
};
export interface WithdrawalDecisionRequest {
    decision: WithdrawalDecisionRequestDecision;
    reason?: string | null;
}
export type DepositMethod = (typeof DepositMethod)[keyof typeof DepositMethod];
export declare const DepositMethod: {
    readonly crypto_wallet: "crypto_wallet";
    readonly bank_transfer: "bank_transfer";
    readonly card: "card";
};
export type DepositStatus = (typeof DepositStatus)[keyof typeof DepositStatus];
export declare const DepositStatus: {
    readonly pending: "pending";
    readonly completed: "completed";
    readonly failed: "failed";
};
export interface Deposit {
    id: string;
    userId: string;
    amount: number;
    currency: string;
    method: DepositMethod;
    status: DepositStatus;
    reference?: string | null;
    createdAt: string;
}
export type DepositRequestMethod = (typeof DepositRequestMethod)[keyof typeof DepositRequestMethod];
export declare const DepositRequestMethod: {
    readonly crypto_wallet: "crypto_wallet";
    readonly bank_transfer: "bank_transfer";
    readonly card: "card";
};
export interface DepositRequest {
    /** @minimum 0.000001 */
    amount: number;
    currency: string;
    method: DepositRequestMethod;
    reference?: string | null;
    /** When method is crypto_wallet and the funds are sent from a connected external wallet, the id of that wallet. */
    externalWalletId?: string | null;
    /** On-chain transaction hash recorded after a successful external_wallet send. */
    txHash?: string | null;
}
export interface BankAccount {
    id: string;
    userId: string;
    bankName: string;
    accountHolder: string;
    last4: string;
    currency: string;
    verified: boolean;
    /** True when this is the user's default payout bank account. */
    isDefault?: boolean;
    /** User-reported (or admin-set) available fiat balance for this bank account. */
    fiatBalance: number;
    /** ISO currency code for the fiat balance (defaults to the bank's currency). */
    fiatCurrency: string;
    createdAt: string;
}
export interface LinkBankRequest {
    bankName: string;
    accountHolder: string;
    accountNumber: string;
    routingNumber: string;
    currency: string;
}
export interface AdminBankSummary {
    id: string;
    userId: string;
    userName: string;
    userEmail: string;
    bankName: string;
    accountHolder: string;
    last4: string;
    currency: string;
    verified: boolean;
    createdAt: string;
}
export interface BankVerificationRequest {
    verified: boolean;
}
export type ReferralEntryStatus = (typeof ReferralEntryStatus)[keyof typeof ReferralEntryStatus];
export declare const ReferralEntryStatus: {
    readonly pending: "pending";
    readonly active: "active";
    readonly expired: "expired";
};
export interface ReferralEntry {
    id: string;
    referredName: string;
    joinedAt: string;
    status: ReferralEntryStatus;
    earned: number;
}
export interface ReferralInfo {
    code: string;
    link: string;
    signups: number;
    activeReferrals: number;
    earnings: number;
    currency: string;
    programDays: number;
    recent: ReferralEntry[];
}
export interface AdminStats {
    totalUsers: number;
    totalDeposits: number;
    totalWithdrawals: number;
    pendingWithdrawals: number;
    pendingKyc: number;
    activeTrades: number;
    currency: string;
}
export type AdminUserSummaryRole = (typeof AdminUserSummaryRole)[keyof typeof AdminUserSummaryRole];
export declare const AdminUserSummaryRole: {
    readonly user: "user";
    readonly admin: "admin";
    readonly demo: "demo";
};
export type AdminUserSummaryKycStatus = (typeof AdminUserSummaryKycStatus)[keyof typeof AdminUserSummaryKycStatus];
export declare const AdminUserSummaryKycStatus: {
    readonly not_submitted: "not_submitted";
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
export interface AdminUserSummary {
    id: string;
    email: string;
    fullName: string;
    country: string;
    role: AdminUserSummaryRole;
    kycStatus: AdminUserSummaryKycStatus;
    balance: number;
    merchant: boolean;
    tradingLocked: boolean;
    /** Admin-set risk flag (e.g. "fraud_review", "watchlist") shown across admin UIs. */
    accountFlag?: string | null;
    /** When true the user is read-only across the platform. */
    suspended: boolean;
    /** When true the user cannot authenticate at all. */
    disabled: boolean;
    createdAt: string;
}
export interface ActivityLogEntry {
    id: string;
    timestamp: string;
    actorId?: string | null;
    actorName?: string | null;
    action: string;
    detail: string;
}
export type BrokerCardType = (typeof BrokerCardType)[keyof typeof BrokerCardType];
export declare const BrokerCardType: {
    readonly debit: "debit";
    readonly credit: "credit";
};
export type BrokerCardBrand = (typeof BrokerCardBrand)[keyof typeof BrokerCardBrand];
export declare const BrokerCardBrand: {
    readonly visa: "visa";
    readonly mastercard: "mastercard";
    readonly amex: "amex";
    readonly xpresspro: "xpresspro";
};
export type BrokerCardStatus = (typeof BrokerCardStatus)[keyof typeof BrokerCardStatus];
export declare const BrokerCardStatus: {
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
    readonly cancelled: "cancelled";
};
export type CardDesignPattern = (typeof CardDesignPattern)[keyof typeof CardDesignPattern];
export declare const CardDesignPattern: {
    readonly solid: "solid";
    readonly gradient: "gradient";
    readonly mesh: "mesh";
    readonly waves: "waves";
    readonly grid: "grid";
    readonly carbon: "carbon";
};
export type CardDesignTextColor = (typeof CardDesignTextColor)[keyof typeof CardDesignTextColor];
export declare const CardDesignTextColor: {
    readonly light: "light";
    readonly dark: "dark";
};
export interface CardDesign {
    /** ID of one of the preset templates (or "custom"). */
    templateId: string;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    pattern: CardDesignPattern;
    textColor: CardDesignTextColor;
}
export interface BrokerCard {
    id: string;
    userId: string;
    type: BrokerCardType;
    brand: BrokerCardBrand;
    status: BrokerCardStatus;
    currency: string;
    /** Last four digits of the card number (masked display only). */
    last4: string;
    /** MM/YY */
    expiry: string;
    holderName: string;
    spendLimit: number;
    creditLimit?: number | null;
    /** Spendable balance for debit cards or available credit for credit cards. */
    balance: number;
    design: CardDesign;
    rejectionReason?: string | null;
    createdAt: string;
    approvedAt?: string | null;
}
export type RequestCardRequestType = (typeof RequestCardRequestType)[keyof typeof RequestCardRequestType];
export declare const RequestCardRequestType: {
    readonly debit: "debit";
    readonly credit: "credit";
};
export type RequestCardRequestBrand = (typeof RequestCardRequestBrand)[keyof typeof RequestCardRequestBrand];
export declare const RequestCardRequestBrand: {
    readonly visa: "visa";
    readonly mastercard: "mastercard";
    readonly amex: "amex";
    readonly xpresspro: "xpresspro";
};
export interface RequestCardRequest {
    type: RequestCardRequestType;
    brand: RequestCardRequestBrand;
    currency: string;
    creditLimit?: number | null;
    design: CardDesign;
}
export interface UpdateCardDesignRequest {
    design: CardDesign;
    holderName?: string;
}
export type AdminCardSummary = BrokerCard & {
    userName: string;
    userEmail: string;
};
export type CardDecisionRequestDecision = (typeof CardDecisionRequestDecision)[keyof typeof CardDecisionRequestDecision];
export declare const CardDecisionRequestDecision: {
    readonly approve: "approve";
    readonly reject: "reject";
};
export interface CardDecisionRequest {
    decision: CardDecisionRequestDecision;
    reason?: string | null;
}
export type PromotionCategory = (typeof PromotionCategory)[keyof typeof PromotionCategory];
export declare const PromotionCategory: {
    readonly bonus: "bonus";
    readonly contest: "contest";
    readonly cashback: "cashback";
    readonly education: "education";
    readonly referral: "referral";
};
export interface Promotion {
    id: string;
    title: string;
    description: string;
    category: PromotionCategory;
    reward: string;
    rewardAmount: number;
    currency: string;
    startsAt: string;
    endsAt: string;
    active: boolean;
    participants: number;
    /** True when the current user is enrolled. */
    joined: boolean;
    createdAt: string;
}
export type CreatePromotionRequestCategory = (typeof CreatePromotionRequestCategory)[keyof typeof CreatePromotionRequestCategory];
export declare const CreatePromotionRequestCategory: {
    readonly bonus: "bonus";
    readonly contest: "contest";
    readonly cashback: "cashback";
    readonly education: "education";
    readonly referral: "referral";
};
export interface CreatePromotionRequest {
    title: string;
    description: string;
    category: CreatePromotionRequestCategory;
    reward: string;
    rewardAmount: number;
    currency: string;
    startsAt: string;
    endsAt: string;
    active: boolean;
}
export type UpdatePromotionRequestCategory = (typeof UpdatePromotionRequestCategory)[keyof typeof UpdatePromotionRequestCategory];
export declare const UpdatePromotionRequestCategory: {
    readonly bonus: "bonus";
    readonly contest: "contest";
    readonly cashback: "cashback";
    readonly education: "education";
    readonly referral: "referral";
};
export interface UpdatePromotionRequest {
    title?: string;
    description?: string;
    category?: UpdatePromotionRequestCategory;
    reward?: string;
    rewardAmount?: number;
    currency?: string;
    startsAt?: string;
    endsAt?: string;
    active?: boolean;
}
/**
 * Monthly mandatory fees applicable to a user.
 */
export interface BillingRates {
    /** Monthly account maintenance fee. */
    maintenance: number;
    /** Monthly AI assistance bot subscription. */
    aiBot: number;
    /** Monthly fee per new active ongoing trade. */
    activeTrade: number;
    currency: string;
}
export type BillingChargeKey = (typeof BillingChargeKey)[keyof typeof BillingChargeKey];
export declare const BillingChargeKey: {
    readonly maintenance: "maintenance";
    readonly aiBot: "aiBot";
    readonly activeTrade: "activeTrade";
};
export interface BillingCharge {
    key: BillingChargeKey;
    label: string;
    amount: number;
    paid: boolean;
    paidAt: string | null;
}
export interface BillingCycle {
    cycleId: string;
    cycleStart: string;
    cycleEnd: string;
    dueAt: string;
    currency: string;
    charges: BillingCharge[];
    totalDue: number;
    totalPaid: number;
    fullySettled: boolean;
}
export interface BillingStatus {
    rates: BillingRates;
    currentCycle: BillingCycle;
    history: BillingCycle[];
    overdue: boolean;
}
export type BillingPaymentRequestItemsItem = (typeof BillingPaymentRequestItemsItem)[keyof typeof BillingPaymentRequestItemsItem];
export declare const BillingPaymentRequestItemsItem: {
    readonly maintenance: "maintenance";
    readonly aiBot: "aiBot";
    readonly activeTrade: "activeTrade";
};
export interface BillingPaymentRequest {
    items: BillingPaymentRequestItemsItem[];
    /** Optional source wallet; defaults to main wallet. */
    walletId?: string | null;
}
export interface AdminBillingUserRow {
    userId: string;
    userName: string;
    userEmail: string;
    rates: BillingRates;
    usingDefaults: boolean;
    currentCycle: BillingCycle;
}
export interface AdminBillingOverview {
    defaults: BillingRates;
    rows: AdminBillingUserRow[];
}
/**
 * Per-action gas-fee policy. Overrides the global default for a
specific money-movement action (e.g. `withdrawal`, `deposit`,
`wallet_transfer`, `asset_purchase`, `p2p_order`,
`trade_release`).

 */
export interface GasFeeActionPolicy {
    /** Whether the gas-fee gate runs for this action. */
    enabled: boolean;
    /** ETH the user must hold across connected wallets. */
    requiredEthAmount: number;
    /** Default per-transaction ETH fee charged on admin approval
  (used as the prefilled value when the admin sets a fee on a
  specific withdrawal).
   */
    defaultFeeAmount: number;
    /** How long the user has to fund the gas fee for this action
  before the request auto-expires.
   */
    deadlineSeconds: number;
    description: string;
}
/**
 * Action-keyed policy overrides.
 */
export type GasFeeSettingsPerAction = {
    [key: string]: GasFeeActionPolicy;
};
/**
 * Platform gas-fee policy. The top-level fields are the global
default; `perAction` overrides individual money-movement actions.

 */
export interface GasFeeSettings {
    /** Default ETH required across all gated actions. */
    requiredEthAmount: number;
    /** Master toggle for the gas-fee gate. */
    enabled: boolean;
    description: string;
    /** Action-keyed policy overrides. */
    perAction?: GasFeeSettingsPerAction;
}
export interface WithdrawalGasFeeStatus {
    enabled: boolean;
    requiredEthAmount: number;
    userEthBalance: number;
    sufficient: boolean;
    message: string;
}
export interface WalletAdjustBody {
    walletId: string;
    /** Positive to add funds, negative to subtract */
    delta: number;
    note?: string;
}
export interface CredentialVault {
    notes?: string | null;
}
/**
 * Map of asset symbol to deposit wallet address (e.g. ETH -> 0x...)
 */
export interface CryptoAddressMap {
    [key: string]: string;
}
export type AdminUserDetailRole = (typeof AdminUserDetailRole)[keyof typeof AdminUserDetailRole];
export declare const AdminUserDetailRole: {
    readonly user: "user";
    readonly admin: "admin";
    readonly demo: "demo";
};
export type AdminUserDetailKycStatus = (typeof AdminUserDetailKycStatus)[keyof typeof AdminUserDetailKycStatus];
export declare const AdminUserDetailKycStatus: {
    readonly not_submitted: "not_submitted";
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
export interface AdminUserDetail {
    userId: string;
    user: User;
    role: AdminUserDetailRole;
    merchant: boolean;
    tradingLocked: boolean;
    socialLocked: boolean;
    demoMode: boolean;
    kycStatus: AdminUserDetailKycStatus;
    wallets: Wallet[];
    bankAccounts: BankAccount[];
    connectedWallets: AdminConnectedWallet[];
    withdrawals: Withdrawal[];
    deposits: Deposit[];
    trades: Trade[];
    cryptoAddresses: CryptoAddressMap;
    accountFlag?: string | null;
    suspended: boolean;
    disabled: boolean;
}
export interface LiveChatMessage {
    id: string;
    userId: string;
    senderName: string;
    content: string;
    isFromUser: boolean;
    isBot: boolean;
    escalated: boolean;
    createdAt: string;
}
export interface LiveChatSession {
    userId: string;
    userName: string;
    userEmail: string;
    messages: LiveChatMessage[];
    lastMessageAt: string;
    escalated: boolean;
    unreadByAdmin: number;
}
export interface SendLiveChatBody {
    content: string;
}
export interface LiveChatResponse {
    userMessage: LiveChatMessage;
    botReply?: LiveChatMessage | null;
    escalated: boolean;
}
export interface AdminChatReplyBody {
    content: string;
}
export interface MailboxMessage {
    id: string;
    from: string;
    content: string;
    /** Optional inline image attachment URL. */
    imageUrl?: string | null;
    createdAt: string;
}
export interface MailboxThread {
    id: string;
    userId: string;
    from: string;
    to: string;
    subject: string;
    messages: MailboxMessage[];
    read: boolean;
    createdAt: string;
    updatedAt: string;
    /** When true, the user cannot reply to this thread (admin-controlled per-thread no-reply enforcement). */
    noReply?: boolean;
}
export interface SendMailBody {
    /** Recipient mailbox (e.g. help@xpressprofx.com) */
    to: string;
    subject: string;
    content: string;
    imageUrl?: string | null;
}
export interface MailboxReplyBody {
    /** Which platform address is replying */
    from: string;
    content: string;
    imageUrl?: string | null;
    /** When true, lock this thread so the user cannot reply to it. */
    noReply?: boolean;
}
export interface MailboxUserReplyBody {
    content: string;
    imageUrl?: string | null;
}
export interface OkResponse {
    ok: boolean;
}
export interface PlatformSettings {
    tradingEnabled: boolean;
    registrationEnabled: boolean;
    demoModeEnabled: boolean;
    maintenanceMode: boolean;
    maintenanceMessage: string;
}
export type CreateAssetRequestCategory = (typeof CreateAssetRequestCategory)[keyof typeof CreateAssetRequestCategory];
export declare const CreateAssetRequestCategory: {
    readonly crypto: "crypto";
    readonly stock: "stock";
    readonly etf: "etf";
    readonly forex: "forex";
    readonly commodity: "commodity";
};
export interface CreateAssetRequest {
    symbol: string;
    name: string;
    category: CreateAssetRequestCategory;
    price: number;
    currency: string;
    imageUrl?: string | null;
}
export type UpdateAssetRequestCategory = (typeof UpdateAssetRequestCategory)[keyof typeof UpdateAssetRequestCategory];
export declare const UpdateAssetRequestCategory: {
    readonly crypto: "crypto";
    readonly stock: "stock";
    readonly etf: "etf";
    readonly forex: "forex";
    readonly commodity: "commodity";
};
export interface UpdateAssetRequest {
    name?: string;
    price?: number;
    currency?: string;
    category?: UpdateAssetRequestCategory;
    change24h?: number;
    imageUrl?: string | null;
    available?: boolean;
}
export type AdminTradeRow = Trade & {
    userId: string;
    userName: string;
    userEmail: string;
};
export type CreateAdminTradeRequestType = (typeof CreateAdminTradeRequestType)[keyof typeof CreateAdminTradeRequestType];
export declare const CreateAdminTradeRequestType: {
    readonly long: "long";
    readonly short: "short";
};
export type CreateAdminTradeRequestStatus = (typeof CreateAdminTradeRequestStatus)[keyof typeof CreateAdminTradeRequestStatus];
export declare const CreateAdminTradeRequestStatus: {
    readonly active: "active";
    readonly completed: "completed";
    readonly cancelled: "cancelled";
};
export interface CreateAdminTradeRequest {
    pair: string;
    type: CreateAdminTradeRequestType;
    amount: number;
    entryPrice: number;
    currentPrice: number;
    targetPrice: number;
    currency: string;
    profit: number;
    expectedProfit: number;
    managerId?: string | null;
    status?: CreateAdminTradeRequestStatus;
}
export type UpdateAdminTradeRequestType = (typeof UpdateAdminTradeRequestType)[keyof typeof UpdateAdminTradeRequestType];
export declare const UpdateAdminTradeRequestType: {
    readonly long: "long";
    readonly short: "short";
};
export type UpdateAdminTradeRequestStatus = (typeof UpdateAdminTradeRequestStatus)[keyof typeof UpdateAdminTradeRequestStatus];
export declare const UpdateAdminTradeRequestStatus: {
    readonly active: "active";
    readonly completed: "completed";
    readonly cancelled: "cancelled";
};
export interface UpdateAdminTradeRequest {
    pair?: string;
    type?: UpdateAdminTradeRequestType;
    amount?: number;
    entryPrice?: number;
    currentPrice?: number;
    targetPrice?: number;
    profit?: number;
    expectedProfit?: number;
    managerId?: string | null;
    status?: UpdateAdminTradeRequestStatus;
}
export type CreateUserRequestRole = (typeof CreateUserRequestRole)[keyof typeof CreateUserRequestRole];
export declare const CreateUserRequestRole: {
    readonly user: "user";
    readonly admin: "admin";
    readonly demo: "demo";
};
export interface CreateUserRequest {
    email: string;
    password: string;
    fullName: string;
    username: string;
    country: string;
    phone?: string | null;
    role: CreateUserRequestRole;
    kycVerified?: boolean;
    merchant?: boolean;
}
export interface UpdateUserProfileRequest {
    fullName?: string;
    username?: string;
    email?: string;
    country?: string;
    phone?: string | null;
    /** New password (omit to leave unchanged) */
    password?: string;
}
export type UpdateUserStatusRequestRole = (typeof UpdateUserStatusRequestRole)[keyof typeof UpdateUserStatusRequestRole];
export declare const UpdateUserStatusRequestRole: {
    readonly user: "user";
    readonly admin: "admin";
    readonly demo: "demo";
};
export interface UpdateUserStatusRequest {
    role?: UpdateUserStatusRequestRole;
    kycVerified?: boolean;
    tradingLocked?: boolean;
    socialLocked?: boolean;
    demoMode?: boolean;
    merchant?: boolean;
    accountFlag?: string | null;
    suspended?: boolean;
    disabled?: boolean;
    /** When true, the user's KYC submission is wiped back to `not_submitted` and they are forced to re-submit. */
    resetKyc?: boolean;
}
export interface UpdateBankAccountRequest {
    bankName?: string;
    accountHolder?: string;
    last4?: string;
    currency?: string;
    verified?: boolean;
    isDefault?: boolean;
    /** Set the user-facing fiat balance shown on the Wallets/Dashboard. */
    fiatBalance?: number;
    /** ISO currency code for the fiat balance. */
    fiatCurrency?: string;
}
export interface UpdateOwnBankAccountRequest {
    /** User self-reported fiat balance for this account. */
    fiatBalance?: number;
    /** Optional override for the fiat currency (defaults to the bank's currency). */
    fiatCurrency?: string;
}
export interface UpdateOwnProfileRequest {
    /** User's MoonPay account email (use empty string or null to unlink). */
    moonpayEmail?: string | null;
}
/**
 * Source of the destination address.
 */
export type MoonpayInitiateRequestDestinationKind = (typeof MoonpayInitiateRequestDestinationKind)[keyof typeof MoonpayInitiateRequestDestinationKind];
export declare const MoonpayInitiateRequestDestinationKind: {
    readonly platform: "platform";
    readonly external: "external";
    readonly custom: "custom";
};
export interface MoonpayInitiateRequest {
    /** Crypto asset symbol to purchase (e.g. BTC, ETH, USDT). */
    assetSymbol: string;
    /**
     * Fiat amount the user wants to spend.
     * @minimum 1
     */
    fiatAmount: number;
    /** Fiat currency code (e.g. USD, EUR). */
    fiatCurrency: string;
    /** Wallet address that should receive the purchased crypto. */
    destinationAddress: string;
    /** Source of the destination address. */
    destinationKind: MoonpayInitiateRequestDestinationKind;
}
export interface MoonpayInitiateResponse {
    /** Hosted MoonPay checkout URL the user should be redirected to. */
    url: string;
    /** True when the URL points at MoonPay sandbox (no live API key configured). */
    sandbox: boolean;
    /** True when the URL was HMAC-signed using the configured MoonPay secret. */
    signed: boolean;
    /** True when MOONPAY_API_KEY is configured server-side. */
    configured: boolean;
    /** True when user identity (email/name) was auto-filled into the URL. */
    autoFilled: boolean;
    /** Optional human-readable notice to surface in the dialog. */
    notice?: string | null;
}
export type MoonpayWebhookEventDataCurrency = {
    code?: string;
} | null;
/**
 * The MoonPay transaction object.
 */
export type MoonpayWebhookEventData = {
    id: string;
    /** e.g. pending, completed, failed. */
    status: string;
    walletAddress?: string | null;
    currency?: MoonpayWebhookEventDataCurrency;
    cryptoTransactionId?: string | null;
    /** Amount of crypto purchased. */
    quoteCurrencyAmount?: number | null;
    /** Fiat amount spent. */
    baseCurrencyAmount?: number | null;
    baseCurrencyCode?: string | null;
    /** Platform user id we passed in the checkout URL. */
    externalCustomerId?: string | null;
    /** Server-generated id we passed at /moonpay/initiate; used to look up the original destination so the webhook only credits platform wallets when the user picked one. */
    externalTransactionId?: string | null;
};
/**
 * A subset of the MoonPay webhook payload we react to.
 */
export interface MoonpayWebhookEvent {
    /** Event type, e.g. "transaction_updated" or "transaction_completed". */
    type: string;
    /** The MoonPay transaction object. */
    data: MoonpayWebhookEventData;
}
/**
 * Primary payment method the merchant will accept buyer funds on.
 */
export type P2PMerchantApplicationPaymentMethod = (typeof P2PMerchantApplicationPaymentMethod)[keyof typeof P2PMerchantApplicationPaymentMethod];
export declare const P2PMerchantApplicationPaymentMethod: {
    readonly etransfer: "etransfer";
    readonly bank: "bank";
};
export type P2PMerchantApplicationStatus = (typeof P2PMerchantApplicationStatus)[keyof typeof P2PMerchantApplicationStatus];
export declare const P2PMerchantApplicationStatus: {
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
export interface P2PMerchantApplication {
    id: string;
    userId: string;
    userName: string;
    userEmail: string;
    displayName: string;
    /** Applicant's legal full name. */
    legalName: string;
    /** Best email address to reach the applicant on. */
    contactEmail: string;
    /** ISO country code where the applicant is based. */
    country: string;
    /** Primary payment method the merchant will accept buyer funds on. */
    paymentMethod: P2PMerchantApplicationPaymentMethod;
    /** E-Transfer / payout email (used when paymentMethod is etransfer). */
    payoutEmail: string;
    /** Bank receiving info (used when paymentMethod is bank). */
    bankInfo: string;
    assets: string;
    reason: string;
    status: P2PMerchantApplicationStatus;
    rejectionReason?: string | null;
    submittedAt: string;
    decidedAt?: string | null;
}
export interface P2PMerchantApplicationOrNull {
    application?: P2PMerchantApplication | null;
    isMerchant: boolean;
}
export type SubmitP2PMerchantApplicationRequestPaymentMethod = (typeof SubmitP2PMerchantApplicationRequestPaymentMethod)[keyof typeof SubmitP2PMerchantApplicationRequestPaymentMethod];
export declare const SubmitP2PMerchantApplicationRequestPaymentMethod: {
    readonly etransfer: "etransfer";
    readonly bank: "bank";
};
export interface SubmitP2PMerchantApplicationRequest {
    displayName: string;
    legalName: string;
    contactEmail: string;
    /** ISO country code (e.g. CA, US, JP). */
    country: string;
    paymentMethod: SubmitP2PMerchantApplicationRequestPaymentMethod;
    /** E-Transfer / payout email. Required when paymentMethod is etransfer. */
    payoutEmail: string;
    /** Bank receiving info. Required when paymentMethod is bank. */
    bankInfo: string;
    assets: string;
    reason: string;
}
export type P2PMerchantDecisionRequestDecision = (typeof P2PMerchantDecisionRequestDecision)[keyof typeof P2PMerchantDecisionRequestDecision];
export declare const P2PMerchantDecisionRequestDecision: {
    readonly approve: "approve";
    readonly reject: "reject";
};
export interface P2PMerchantDecisionRequest {
    decision: P2PMerchantDecisionRequestDecision;
    reason?: string | null;
}
export interface AdminP2PMerchantSummary {
    userId: string;
    userName: string;
    userEmail: string;
    displayName: string;
    approvedAt?: string | null;
    totalListings: number;
}
export interface AdminP2PMerchantsResponse {
    applications: P2PMerchantApplication[];
    merchants: AdminP2PMerchantSummary[];
}
/**
 * Notification flavour. `deposit_*` variants surface amount/reference/instructions.
 */
export type AdminP2PNotifyRequestKind = (typeof AdminP2PNotifyRequestKind)[keyof typeof AdminP2PNotifyRequestKind];
export declare const AdminP2PNotifyRequestKind: {
    readonly general: "general";
    readonly deposit_incoming: "deposit_incoming";
    readonly deposit_confirmed: "deposit_confirmed";
    readonly p2p_deposit: "p2p_deposit";
    readonly order_update: "order_update";
};
export interface AdminP2PNotifyRequest {
    /** Notification flavour. `deposit_*` variants surface amount/reference/instructions. */
    kind?: AdminP2PNotifyRequestKind;
    title: string;
    message: string;
    /** For deposit notifications, the deposit amount in `currency`. */
    amount?: number | null;
    currency?: string | null;
    /** Asset symbol the deposit relates to (e.g. BTC, USDT). */
    asset?: string | null;
    /** External reference (txid, wire ref, escrow id). */
    reference?: string | null;
    /** Free-form follow-up instructions for the merchant. */
    instructions?: string | null;
}
export interface SendAdminP2PChatRequest {
    content: string;
}
export interface Notification {
    id: string;
    userId: string;
    /** Notification category (e.g. withdrawal_gas_fee_required, account_suspended). */
    kind: string;
    title: string;
    body: string;
    read: boolean;
    /** Optional in-app deep link to surface alongside the notification. */
    link?: string | null;
    createdAt: string;
}
export type AdminAlertSeverity = (typeof AdminAlertSeverity)[keyof typeof AdminAlertSeverity];
export declare const AdminAlertSeverity: {
    readonly info: "info";
    readonly warning: "warning";
    readonly critical: "critical";
};
export interface AdminAlert {
    id: string;
    kind: string;
    title: string;
    body: string;
    userId?: string | null;
    userEmail?: string | null;
    severity: AdminAlertSeverity;
    read: boolean;
    createdAt: string;
    /** Admin portal deep-link the alert should navigate to when clicked. */
    linkUrl?: string | null;
}
/**
 * Admin-controlled toggle map for emailing the user when each kind of
platform event happens. In-app notifications are always created;
these flags only affect the email side-channel.

 */
export interface NotificationSettings {
    withdrawalGasFeeRequired: boolean;
    withdrawalApproved: boolean;
    withdrawalRejected: boolean;
    withdrawalExpired: boolean;
    kycApproved: boolean;
    kycRejected: boolean;
    kycReset: boolean;
    accountSuspended: boolean;
    accountDisabled: boolean;
    accountFlagged: boolean;
    broadcastTicket: boolean;
    mailboxReply: boolean;
    liveChatHandoff: boolean;
    withdrawalSubmitted: boolean;
    depositReceived: boolean;
    p2pOrderUpdate: boolean;
    tradeOpened: boolean;
    walletTransfer: boolean;
}
export interface SentEmail {
    id: string;
    to: string;
    from: string;
    subject: string;
    body: string;
    kind: string;
    sentAt: string;
}
export type BroadcastSupportTicketBodyPriority = (typeof BroadcastSupportTicketBodyPriority)[keyof typeof BroadcastSupportTicketBodyPriority];
export declare const BroadcastSupportTicketBodyPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
    readonly urgent: "urgent";
};
/**
 * ticket = create a personal support ticket per recipient; mailbox = create a mailbox thread.
 */
export type BroadcastSupportTicketBodyMode = (typeof BroadcastSupportTicketBodyMode)[keyof typeof BroadcastSupportTicketBodyMode];
export declare const BroadcastSupportTicketBodyMode: {
    readonly ticket: "ticket";
    readonly mailbox: "mailbox";
};
export type BroadcastSupportTicketBodyFiltersKycStatus = (typeof BroadcastSupportTicketBodyFiltersKycStatus)[keyof typeof BroadcastSupportTicketBodyFiltersKycStatus];
export declare const BroadcastSupportTicketBodyFiltersKycStatus: {
    readonly any: "any";
    readonly not_submitted: "not_submitted";
    readonly pending: "pending";
    readonly approved: "approved";
    readonly rejected: "rejected";
};
export type BroadcastSupportTicketBodyFiltersMerchant = (typeof BroadcastSupportTicketBodyFiltersMerchant)[keyof typeof BroadcastSupportTicketBodyFiltersMerchant];
export declare const BroadcastSupportTicketBodyFiltersMerchant: {
    readonly any: "any";
    readonly only: "only";
    readonly exclude: "exclude";
};
/**
 * Recipient filters. Omit for all non-admin users.
 */
export type BroadcastSupportTicketBodyFilters = {
    kycStatus?: BroadcastSupportTicketBodyFiltersKycStatus;
    country?: string | null;
    merchant?: BroadcastSupportTicketBodyFiltersMerchant;
};
export interface BroadcastSupportTicketBody {
    subject: string;
    message: string;
    /** Optional image attachment URL persisted on the broadcast
  payload (mailbox message or support ticket message).
   */
    imageUrl?: string | null;
    priority: BroadcastSupportTicketBodyPriority;
    /** ticket = create a personal support ticket per recipient; mailbox = create a mailbox thread. */
    mode?: BroadcastSupportTicketBodyMode;
    /** Recipient filters. Omit for all non-admin users. */
    filters?: BroadcastSupportTicketBodyFilters;
}
export type BroadcastResultMode = (typeof BroadcastResultMode)[keyof typeof BroadcastResultMode];
export declare const BroadcastResultMode: {
    readonly ticket: "ticket";
    readonly mailbox: "mailbox";
};
export interface BroadcastResult {
    recipients: number;
    mode?: BroadcastResultMode;
    /** Number of users that did not match the filters. */
    skipped?: number;
}
export type AdminPresenceStateAdminsItem = {
    userId: string;
    email: string;
    fullName: string;
    lastSeenAt: string;
};
export interface AdminPresenceState {
    onlineAdminCount: number;
    anyOnline: boolean;
    admins: AdminPresenceStateAdminsItem[];
}
export interface AdminSetWithdrawalGasFeeBody {
    /**
     * ETH amount the user must fund as gas fee.
     * @minimum 0
     */
    gasFeeAmount: number;
    /**
     * Minutes from now that the user has to fund the fee before the withdrawal expires.
     * @minimum 1
     */
    deadlineMinutes: number;
}
export interface MarkGasFeeFundedBody {
    /** On-chain tx hash proving the user funded the gas fee. */
    txHash: string;
}
export type GetMessagesParams = {
    context?: GetMessagesContext;
    contextId?: string;
};
export type GetMessagesContext = (typeof GetMessagesContext)[keyof typeof GetMessagesContext];
export declare const GetMessagesContext: {
    readonly manager: "manager";
    readonly p2p: "p2p";
    readonly support: "support";
};
export type GetP2PListingsParams = {
    type?: GetP2PListingsType;
    asset?: string;
};
export type GetP2PListingsType = (typeof GetP2PListingsType)[keyof typeof GetP2PListingsType];
export declare const GetP2PListingsType: {
    readonly buy: "buy";
    readonly sell: "sell";
};
export type GetAdminWithdrawalsParams = {
    status?: GetAdminWithdrawalsStatus;
};
export type GetAdminWithdrawalsStatus = (typeof GetAdminWithdrawalsStatus)[keyof typeof GetAdminWithdrawalsStatus];
export declare const GetAdminWithdrawalsStatus: {
    readonly pending: "pending";
    readonly awaiting_gas_fee: "awaiting_gas_fee";
    readonly approved: "approved";
    readonly rejected: "rejected";
    readonly completed: "completed";
    readonly cancelled: "cancelled";
    readonly expired: "expired";
};
//# sourceMappingURL=api.schemas.d.ts.map