/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AccountManager,
  ActionResult,
  AssetCatalogItem,
  ConnectWalletRequest,
  ConnectedWallet,
  CreateP2PListingRequest,
  CreateP2POrderRequest,
  CreateSupportTicketRequest,
  GetMessagesParams,
  GetP2PListingsParams,
  HealthStatus,
  Message,
  P2PListing,
  P2PNotification,
  P2POrder,
  PurchaseAssetRequest,
  PurchaseResult,
  SelectManagerRequest,
  SelectedManagerResponse,
  SendMessageRequest,
  SocialTradingWallet,
  SupportTicket,
  Trade,
  Transaction,
  User,
  Wallet,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current user profile
 */
export const getGetCurrentUserUrl = () => {
  return `/api/users/me`;
};

export const getCurrentUser = async (options?: RequestInit): Promise<User> => {
  return customFetch<User>(getGetCurrentUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentUserQueryKey = () => {
  return [`/api/users/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = ErrorType<unknown>;

/**
 * @summary Get current user profile
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user wallets
 */
export const getGetWalletsUrl = () => {
  return `/api/wallets`;
};

export const getWallets = async (options?: RequestInit): Promise<Wallet[]> => {
  return customFetch<Wallet[]>(getGetWalletsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWalletsQueryKey = () => {
  return [`/api/wallets`] as const;
};

export const getGetWalletsQueryOptions = <
  TData = Awaited<ReturnType<typeof getWallets>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWallets>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWalletsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWallets>>> = ({
    signal,
  }) => getWallets({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWallets>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWalletsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWallets>>
>;
export type GetWalletsQueryError = ErrorType<unknown>;

/**
 * @summary Get user wallets
 */

export function useGetWallets<
  TData = Awaited<ReturnType<typeof getWallets>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWallets>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWalletsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get wallet transactions
 */
export const getGetTransactionsUrl = () => {
  return `/api/wallets/transactions`;
};

export const getTransactions = async (
  options?: RequestInit,
): Promise<Transaction[]> => {
  return customFetch<Transaction[]>(getGetTransactionsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetTransactionsQueryKey = () => {
  return [`/api/wallets/transactions`] as const;
};

export const getGetTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTransactionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactions>>> = ({
    signal,
  }) => getTransactions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactions>>
>;
export type GetTransactionsQueryError = ErrorType<unknown>;

/**
 * @summary Get wallet transactions
 */

export function useGetTransactions<
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTransactionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Connect an external wallet
 */
export const getConnectExternalWalletUrl = () => {
  return `/api/wallets/connect`;
};

export const connectExternalWallet = async (
  connectWalletRequest: ConnectWalletRequest,
  options?: RequestInit,
): Promise<ConnectedWallet> => {
  return customFetch<ConnectedWallet>(getConnectExternalWalletUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(connectWalletRequest),
  });
};

export const getConnectExternalWalletMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectExternalWallet>>,
    TError,
    { data: BodyType<ConnectWalletRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof connectExternalWallet>>,
  TError,
  { data: BodyType<ConnectWalletRequest> },
  TContext
> => {
  const mutationKey = ["connectExternalWallet"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof connectExternalWallet>>,
    { data: BodyType<ConnectWalletRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return connectExternalWallet(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConnectExternalWalletMutationResult = NonNullable<
  Awaited<ReturnType<typeof connectExternalWallet>>
>;
export type ConnectExternalWalletMutationBody = BodyType<ConnectWalletRequest>;
export type ConnectExternalWalletMutationError = ErrorType<unknown>;

/**
 * @summary Connect an external wallet
 */
export const useConnectExternalWallet = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectExternalWallet>>,
    TError,
    { data: BodyType<ConnectWalletRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof connectExternalWallet>>,
  TError,
  { data: BodyType<ConnectWalletRequest> },
  TContext
> => {
  return useMutation(getConnectExternalWalletMutationOptions(options));
};

/**
 * @summary Get user trades
 */
export const getGetTradesUrl = () => {
  return `/api/trades`;
};

export const getTrades = async (options?: RequestInit): Promise<Trade[]> => {
  return customFetch<Trade[]>(getGetTradesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetTradesQueryKey = () => {
  return [`/api/trades`] as const;
};

export const getGetTradesQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrades>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getTrades>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTradesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrades>>> = ({
    signal,
  }) => getTrades({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTrades>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTradesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrades>>
>;
export type GetTradesQueryError = ErrorType<unknown>;

/**
 * @summary Get user trades
 */

export function useGetTrades<
  TData = Awaited<ReturnType<typeof getTrades>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getTrades>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTradesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get social trading wallet summary
 */
export const getGetSocialTradingWalletUrl = () => {
  return `/api/trades/social-wallet`;
};

export const getSocialTradingWallet = async (
  options?: RequestInit,
): Promise<SocialTradingWallet> => {
  return customFetch<SocialTradingWallet>(getGetSocialTradingWalletUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSocialTradingWalletQueryKey = () => {
  return [`/api/trades/social-wallet`] as const;
};

export const getGetSocialTradingWalletQueryOptions = <
  TData = Awaited<ReturnType<typeof getSocialTradingWallet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSocialTradingWallet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSocialTradingWalletQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSocialTradingWallet>>
  > = ({ signal }) => getSocialTradingWallet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSocialTradingWallet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSocialTradingWalletQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSocialTradingWallet>>
>;
export type GetSocialTradingWalletQueryError = ErrorType<unknown>;

/**
 * @summary Get social trading wallet summary
 */

export function useGetSocialTradingWallet<
  TData = Awaited<ReturnType<typeof getSocialTradingWallet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSocialTradingWallet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSocialTradingWalletQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Release completed trade funds to main wallet
 */
export const getReleaseTradeFundsUrl = (tradeId: string) => {
  return `/api/trades/${tradeId}/release`;
};

export const releaseTradeFunds = async (
  tradeId: string,
  options?: RequestInit,
): Promise<ActionResult> => {
  return customFetch<ActionResult>(getReleaseTradeFundsUrl(tradeId), {
    ...options,
    method: "POST",
  });
};

export const getReleaseTradeFundsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof releaseTradeFunds>>,
    TError,
    { tradeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof releaseTradeFunds>>,
  TError,
  { tradeId: string },
  TContext
> => {
  const mutationKey = ["releaseTradeFunds"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof releaseTradeFunds>>,
    { tradeId: string }
  > = (props) => {
    const { tradeId } = props ?? {};

    return releaseTradeFunds(tradeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReleaseTradeFundsMutationResult = NonNullable<
  Awaited<ReturnType<typeof releaseTradeFunds>>
>;

export type ReleaseTradeFundsMutationError = ErrorType<unknown>;

/**
 * @summary Release completed trade funds to main wallet
 */
export const useReleaseTradeFunds = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof releaseTradeFunds>>,
    TError,
    { tradeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof releaseTradeFunds>>,
  TError,
  { tradeId: string },
  TContext
> => {
  return useMutation(getReleaseTradeFundsMutationOptions(options));
};

/**
 * @summary Get list of account managers
 */
export const getGetManagersUrl = () => {
  return `/api/managers`;
};

export const getManagers = async (
  options?: RequestInit,
): Promise<AccountManager[]> => {
  return customFetch<AccountManager[]>(getGetManagersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetManagersQueryKey = () => {
  return [`/api/managers`] as const;
};

export const getGetManagersQueryOptions = <
  TData = Awaited<ReturnType<typeof getManagers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getManagers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetManagersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getManagers>>> = ({
    signal,
  }) => getManagers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getManagers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetManagersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getManagers>>
>;
export type GetManagersQueryError = ErrorType<unknown>;

/**
 * @summary Get list of account managers
 */

export function useGetManagers<
  TData = Awaited<ReturnType<typeof getManagers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getManagers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetManagersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user's selected account manager
 */
export const getGetSelectedManagerUrl = () => {
  return `/api/managers/selected`;
};

export const getSelectedManager = async (
  options?: RequestInit,
): Promise<SelectedManagerResponse> => {
  return customFetch<SelectedManagerResponse>(getGetSelectedManagerUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSelectedManagerQueryKey = () => {
  return [`/api/managers/selected`] as const;
};

export const getGetSelectedManagerQueryOptions = <
  TData = Awaited<ReturnType<typeof getSelectedManager>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSelectedManager>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSelectedManagerQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSelectedManager>>
  > = ({ signal }) => getSelectedManager({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSelectedManager>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSelectedManagerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSelectedManager>>
>;
export type GetSelectedManagerQueryError = ErrorType<unknown>;

/**
 * @summary Get user's selected account manager
 */

export function useGetSelectedManager<
  TData = Awaited<ReturnType<typeof getSelectedManager>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSelectedManager>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSelectedManagerQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Select an account manager
 */
export const getSelectManagerUrl = () => {
  return `/api/managers/selected`;
};

export const selectManager = async (
  selectManagerRequest: SelectManagerRequest,
  options?: RequestInit,
): Promise<ActionResult> => {
  return customFetch<ActionResult>(getSelectManagerUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(selectManagerRequest),
  });
};

export const getSelectManagerMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectManager>>,
    TError,
    { data: BodyType<SelectManagerRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof selectManager>>,
  TError,
  { data: BodyType<SelectManagerRequest> },
  TContext
> => {
  const mutationKey = ["selectManager"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof selectManager>>,
    { data: BodyType<SelectManagerRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return selectManager(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SelectManagerMutationResult = NonNullable<
  Awaited<ReturnType<typeof selectManager>>
>;
export type SelectManagerMutationBody = BodyType<SelectManagerRequest>;
export type SelectManagerMutationError = ErrorType<unknown>;

/**
 * @summary Select an account manager
 */
export const useSelectManager = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectManager>>,
    TError,
    { data: BodyType<SelectManagerRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof selectManager>>,
  TError,
  { data: BodyType<SelectManagerRequest> },
  TContext
> => {
  return useMutation(getSelectManagerMutationOptions(options));
};

/**
 * @summary Get messages with manager or in P2P context
 */
export const getGetMessagesUrl = (params?: GetMessagesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/messages?${stringifiedParams}`
    : `/api/messages`;
};

export const getMessages = async (
  params?: GetMessagesParams,
  options?: RequestInit,
): Promise<Message[]> => {
  return customFetch<Message[]>(getGetMessagesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMessagesQueryKey = (params?: GetMessagesParams) => {
  return [`/api/messages`, ...(params ? [params] : [])] as const;
};

export const getGetMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMessages>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMessagesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMessagesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessages>>> = ({
    signal,
  }) => getMessages(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMessages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMessages>>
>;
export type GetMessagesQueryError = ErrorType<unknown>;

/**
 * @summary Get messages with manager or in P2P context
 */

export function useGetMessages<
  TData = Awaited<ReturnType<typeof getMessages>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMessagesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMessagesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Send a message
 */
export const getSendMessageUrl = () => {
  return `/api/messages`;
};

export const sendMessage = async (
  sendMessageRequest: SendMessageRequest,
  options?: RequestInit,
): Promise<Message> => {
  return customFetch<Message>(getSendMessageUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendMessageRequest),
  });
};

export const getSendMessageMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendMessage>>,
    TError,
    { data: BodyType<SendMessageRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendMessage>>,
  TError,
  { data: BodyType<SendMessageRequest> },
  TContext
> => {
  const mutationKey = ["sendMessage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendMessage>>,
    { data: BodyType<SendMessageRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return sendMessage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendMessage>>
>;
export type SendMessageMutationBody = BodyType<SendMessageRequest>;
export type SendMessageMutationError = ErrorType<unknown>;

/**
 * @summary Send a message
 */
export const useSendMessage = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendMessage>>,
    TError,
    { data: BodyType<SendMessageRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendMessage>>,
  TError,
  { data: BodyType<SendMessageRequest> },
  TContext
> => {
  return useMutation(getSendMessageMutationOptions(options));
};

/**
 * @summary Get P2P marketplace listings
 */
export const getGetP2PListingsUrl = (params?: GetP2PListingsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/p2p/listings?${stringifiedParams}`
    : `/api/p2p/listings`;
};

export const getP2PListings = async (
  params?: GetP2PListingsParams,
  options?: RequestInit,
): Promise<P2PListing[]> => {
  return customFetch<P2PListing[]>(getGetP2PListingsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetP2PListingsQueryKey = (params?: GetP2PListingsParams) => {
  return [`/api/p2p/listings`, ...(params ? [params] : [])] as const;
};

export const getGetP2PListingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getP2PListings>>,
  TError = ErrorType<unknown>,
>(
  params?: GetP2PListingsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getP2PListings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetP2PListingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getP2PListings>>> = ({
    signal,
  }) => getP2PListings(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getP2PListings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetP2PListingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getP2PListings>>
>;
export type GetP2PListingsQueryError = ErrorType<unknown>;

/**
 * @summary Get P2P marketplace listings
 */

export function useGetP2PListings<
  TData = Awaited<ReturnType<typeof getP2PListings>>,
  TError = ErrorType<unknown>,
>(
  params?: GetP2PListingsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getP2PListings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetP2PListingsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new P2P listing
 */
export const getCreateP2PListingUrl = () => {
  return `/api/p2p/listings`;
};

export const createP2PListing = async (
  createP2PListingRequest: CreateP2PListingRequest,
  options?: RequestInit,
): Promise<P2PListing> => {
  return customFetch<P2PListing>(getCreateP2PListingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createP2PListingRequest),
  });
};

export const getCreateP2PListingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createP2PListing>>,
    TError,
    { data: BodyType<CreateP2PListingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createP2PListing>>,
  TError,
  { data: BodyType<CreateP2PListingRequest> },
  TContext
> => {
  const mutationKey = ["createP2PListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createP2PListing>>,
    { data: BodyType<CreateP2PListingRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createP2PListing(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateP2PListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createP2PListing>>
>;
export type CreateP2PListingMutationBody = BodyType<CreateP2PListingRequest>;
export type CreateP2PListingMutationError = ErrorType<unknown>;

/**
 * @summary Create a new P2P listing
 */
export const useCreateP2PListing = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createP2PListing>>,
    TError,
    { data: BodyType<CreateP2PListingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createP2PListing>>,
  TError,
  { data: BodyType<CreateP2PListingRequest> },
  TContext
> => {
  return useMutation(getCreateP2PListingMutationOptions(options));
};

/**
 * @summary Get user's P2P orders
 */
export const getGetP2POrdersUrl = () => {
  return `/api/p2p/orders`;
};

export const getP2POrders = async (
  options?: RequestInit,
): Promise<P2POrder[]> => {
  return customFetch<P2POrder[]>(getGetP2POrdersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetP2POrdersQueryKey = () => {
  return [`/api/p2p/orders`] as const;
};

export const getGetP2POrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof getP2POrders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getP2POrders>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetP2POrdersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getP2POrders>>> = ({
    signal,
  }) => getP2POrders({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getP2POrders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetP2POrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getP2POrders>>
>;
export type GetP2POrdersQueryError = ErrorType<unknown>;

/**
 * @summary Get user's P2P orders
 */

export function useGetP2POrders<
  TData = Awaited<ReturnType<typeof getP2POrders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getP2POrders>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetP2POrdersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a P2P order (initiate trade)
 */
export const getCreateP2POrderUrl = () => {
  return `/api/p2p/orders`;
};

export const createP2POrder = async (
  createP2POrderRequest: CreateP2POrderRequest,
  options?: RequestInit,
): Promise<P2POrder> => {
  return customFetch<P2POrder>(getCreateP2POrderUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createP2POrderRequest),
  });
};

export const getCreateP2POrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createP2POrder>>,
    TError,
    { data: BodyType<CreateP2POrderRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createP2POrder>>,
  TError,
  { data: BodyType<CreateP2POrderRequest> },
  TContext
> => {
  const mutationKey = ["createP2POrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createP2POrder>>,
    { data: BodyType<CreateP2POrderRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createP2POrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateP2POrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createP2POrder>>
>;
export type CreateP2POrderMutationBody = BodyType<CreateP2POrderRequest>;
export type CreateP2POrderMutationError = ErrorType<unknown>;

/**
 * @summary Create a P2P order (initiate trade)
 */
export const useCreateP2POrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createP2POrder>>,
    TError,
    { data: BodyType<CreateP2POrderRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createP2POrder>>,
  TError,
  { data: BodyType<CreateP2POrderRequest> },
  TContext
> => {
  return useMutation(getCreateP2POrderMutationOptions(options));
};

/**
 * @summary Get P2P admin notifications
 */
export const getGetP2PNotificationsUrl = () => {
  return `/api/p2p/notifications`;
};

export const getP2PNotifications = async (
  options?: RequestInit,
): Promise<P2PNotification[]> => {
  return customFetch<P2PNotification[]>(getGetP2PNotificationsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetP2PNotificationsQueryKey = () => {
  return [`/api/p2p/notifications`] as const;
};

export const getGetP2PNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getP2PNotifications>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getP2PNotifications>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetP2PNotificationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getP2PNotifications>>
  > = ({ signal }) => getP2PNotifications({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getP2PNotifications>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetP2PNotificationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getP2PNotifications>>
>;
export type GetP2PNotificationsQueryError = ErrorType<unknown>;

/**
 * @summary Get P2P admin notifications
 */

export function useGetP2PNotifications<
  TData = Awaited<ReturnType<typeof getP2PNotifications>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getP2PNotifications>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetP2PNotificationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get available assets to purchase
 */
export const getGetAssetCatalogUrl = () => {
  return `/api/assets/catalog`;
};

export const getAssetCatalog = async (
  options?: RequestInit,
): Promise<AssetCatalogItem[]> => {
  return customFetch<AssetCatalogItem[]>(getGetAssetCatalogUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAssetCatalogQueryKey = () => {
  return [`/api/assets/catalog`] as const;
};

export const getGetAssetCatalogQueryOptions = <
  TData = Awaited<ReturnType<typeof getAssetCatalog>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAssetCatalog>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAssetCatalogQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetCatalog>>> = ({
    signal,
  }) => getAssetCatalog({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAssetCatalog>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAssetCatalogQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAssetCatalog>>
>;
export type GetAssetCatalogQueryError = ErrorType<unknown>;

/**
 * @summary Get available assets to purchase
 */

export function useGetAssetCatalog<
  TData = Awaited<ReturnType<typeof getAssetCatalog>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAssetCatalog>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAssetCatalogQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Purchase an asset
 */
export const getPurchaseAssetUrl = () => {
  return `/api/assets/purchase`;
};

export const purchaseAsset = async (
  purchaseAssetRequest: PurchaseAssetRequest,
  options?: RequestInit,
): Promise<PurchaseResult> => {
  return customFetch<PurchaseResult>(getPurchaseAssetUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(purchaseAssetRequest),
  });
};

export const getPurchaseAssetMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchaseAsset>>,
    TError,
    { data: BodyType<PurchaseAssetRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchaseAsset>>,
  TError,
  { data: BodyType<PurchaseAssetRequest> },
  TContext
> => {
  const mutationKey = ["purchaseAsset"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchaseAsset>>,
    { data: BodyType<PurchaseAssetRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return purchaseAsset(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PurchaseAssetMutationResult = NonNullable<
  Awaited<ReturnType<typeof purchaseAsset>>
>;
export type PurchaseAssetMutationBody = BodyType<PurchaseAssetRequest>;
export type PurchaseAssetMutationError = ErrorType<unknown>;

/**
 * @summary Purchase an asset
 */
export const usePurchaseAsset = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchaseAsset>>,
    TError,
    { data: BodyType<PurchaseAssetRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof purchaseAsset>>,
  TError,
  { data: BodyType<PurchaseAssetRequest> },
  TContext
> => {
  return useMutation(getPurchaseAssetMutationOptions(options));
};

/**
 * @summary Get user support tickets
 */
export const getGetSupportTicketsUrl = () => {
  return `/api/support/tickets`;
};

export const getSupportTickets = async (
  options?: RequestInit,
): Promise<SupportTicket[]> => {
  return customFetch<SupportTicket[]>(getGetSupportTicketsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSupportTicketsQueryKey = () => {
  return [`/api/support/tickets`] as const;
};

export const getGetSupportTicketsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSupportTickets>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSupportTickets>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSupportTicketsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSupportTickets>>
  > = ({ signal }) => getSupportTickets({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSupportTickets>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSupportTicketsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSupportTickets>>
>;
export type GetSupportTicketsQueryError = ErrorType<unknown>;

/**
 * @summary Get user support tickets
 */

export function useGetSupportTickets<
  TData = Awaited<ReturnType<typeof getSupportTickets>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSupportTickets>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSupportTicketsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a support ticket
 */
export const getCreateSupportTicketUrl = () => {
  return `/api/support/tickets`;
};

export const createSupportTicket = async (
  createSupportTicketRequest: CreateSupportTicketRequest,
  options?: RequestInit,
): Promise<SupportTicket> => {
  return customFetch<SupportTicket>(getCreateSupportTicketUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSupportTicketRequest),
  });
};

export const getCreateSupportTicketMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSupportTicket>>,
    TError,
    { data: BodyType<CreateSupportTicketRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSupportTicket>>,
  TError,
  { data: BodyType<CreateSupportTicketRequest> },
  TContext
> => {
  const mutationKey = ["createSupportTicket"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSupportTicket>>,
    { data: BodyType<CreateSupportTicketRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createSupportTicket(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSupportTicketMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSupportTicket>>
>;
export type CreateSupportTicketMutationBody =
  BodyType<CreateSupportTicketRequest>;
export type CreateSupportTicketMutationError = ErrorType<unknown>;

/**
 * @summary Create a support ticket
 */
export const useCreateSupportTicket = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSupportTicket>>,
    TError,
    { data: BodyType<CreateSupportTicketRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createSupportTicket>>,
  TError,
  { data: BodyType<CreateSupportTicketRequest> },
  TContext
> => {
  return useMutation(getCreateSupportTicketMutationOptions(options));
};
