/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get current user profile
 */
export const GetCurrentUserResponse = zod.object({
  id: zod.string(),
  username: zod.string(),
  email: zod.string(),
  fullName: zod.string(),
  country: zod.string(),
  kycVerified: zod.boolean(),
  avatarUrl: zod.string().optional(),
  createdAt: zod.string(),
  selectedManagerId: zod.string().nullish(),
});

/**
 * @summary Get user wallets
 */
export const GetWalletsResponseItem = zod.object({
  id: zod.string(),
  type: zod.enum(["main", "trading", "social"]),
  label: zod.string(),
  currency: zod.string(),
  balance: zod.number(),
  pendingBalance: zod.number(),
  address: zod.string(),
});
export const GetWalletsResponse = zod.array(GetWalletsResponseItem);

/**
 * @summary Get wallet transactions
 */
export const GetTransactionsResponseItem = zod.object({
  id: zod.string(),
  walletId: zod.string(),
  type: zod.enum([
    "deposit",
    "withdrawal",
    "trade_profit",
    "p2p_buy",
    "p2p_sell",
    "transfer",
  ]),
  amount: zod.number(),
  currency: zod.string(),
  status: zod.enum(["pending", "completed", "failed"]),
  description: zod.string(),
  createdAt: zod.string(),
});
export const GetTransactionsResponse = zod.array(GetTransactionsResponseItem);

/**
 * @summary Connect an external wallet
 */
export const ConnectExternalWalletBody = zod.object({
  method: zod.enum(["seed_phrase", "private_key"]),
  value: zod.string(),
  walletType: zod.enum(["metamask", "trust", "custom"]),
});

export const ConnectExternalWalletResponse = zod.object({
  id: zod.string(),
  address: zod.string(),
  walletType: zod.string(),
  balance: zod.number(),
  currency: zod.string(),
  connectedAt: zod.string(),
});

/**
 * @summary Get user trades
 */
export const GetTradesResponseItem = zod.object({
  id: zod.string(),
  pair: zod.string(),
  type: zod.enum(["long", "short"]),
  status: zod.enum(["active", "completed", "cancelled"]),
  entryPrice: zod.number(),
  currentPrice: zod.number(),
  targetPrice: zod.number(),
  amount: zod.number(),
  currency: zod.string(),
  profit: zod.number(),
  expectedProfit: zod.number(),
  managerId: zod.string().nullish(),
  createdAt: zod.string(),
  completedAt: zod.string().nullish(),
});
export const GetTradesResponse = zod.array(GetTradesResponseItem);

/**
 * @summary Get social trading wallet summary
 */
export const GetSocialTradingWalletResponse = zod.object({
  totalProfits: zod.number(),
  pendingProfits: zod.number(),
  currency: zod.string(),
  locked: zod.boolean(),
  activeTrades: zod.number(),
});

/**
 * @summary Release completed trade funds to main wallet
 */
export const ReleaseTradeFundsParams = zod.object({
  tradeId: zod.coerce.string(),
});

export const ReleaseTradeFundsResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary Get list of account managers
 */
export const GetManagersResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  avatarUrl: zod.string().optional(),
  title: zod.string(),
  experience: zod.number(),
  strategy: zod.string(),
  performance: zod.number(),
  totalClients: zod.number(),
  winRate: zod.number(),
  specialization: zod.string(),
  bio: zod.string(),
  contactEmail: zod.string(),
  available: zod.boolean(),
});
export const GetManagersResponse = zod.array(GetManagersResponseItem);

/**
 * @summary Get user's selected account manager
 */
export const GetSelectedManagerResponse = zod.object({
  manager: zod
    .object({
      id: zod.string(),
      name: zod.string(),
      avatarUrl: zod.string().optional(),
      title: zod.string(),
      experience: zod.number(),
      strategy: zod.string(),
      performance: zod.number(),
      totalClients: zod.number(),
      winRate: zod.number(),
      specialization: zod.string(),
      bio: zod.string(),
      contactEmail: zod.string(),
      available: zod.boolean(),
    })
    .nullable(),
});

/**
 * @summary Select an account manager
 */
export const SelectManagerBody = zod.object({
  managerId: zod.string(),
});

export const SelectManagerResponse = zod.object({
  success: zod.boolean(),
  message: zod.string(),
});

/**
 * @summary Get messages with manager or in P2P context
 */
export const GetMessagesQueryParams = zod.object({
  context: zod.enum(["manager", "p2p", "support"]).optional(),
  contextId: zod.coerce.string().optional(),
});

export const GetMessagesResponseItem = zod.object({
  id: zod.string(),
  senderId: zod.string(),
  senderName: zod.string(),
  senderAvatar: zod.string().nullish(),
  content: zod.string(),
  context: zod.enum(["manager", "p2p", "support"]),
  contextId: zod.string().nullish(),
  isFromUser: zod.boolean(),
  createdAt: zod.string(),
});
export const GetMessagesResponse = zod.array(GetMessagesResponseItem);

/**
 * @summary Send a message
 */
export const SendMessageBody = zod.object({
  content: zod.string(),
  context: zod.enum(["manager", "p2p", "support"]),
  contextId: zod.string().nullish(),
});

export const SendMessageResponse = zod.object({
  id: zod.string(),
  senderId: zod.string(),
  senderName: zod.string(),
  senderAvatar: zod.string().nullish(),
  content: zod.string(),
  context: zod.enum(["manager", "p2p", "support"]),
  contextId: zod.string().nullish(),
  isFromUser: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Get P2P marketplace listings
 */
export const GetP2PListingsQueryParams = zod.object({
  type: zod.enum(["buy", "sell"]).optional(),
  asset: zod.coerce.string().optional(),
});

export const GetP2PListingsResponseItem = zod.object({
  id: zod.string(),
  userId: zod.string(),
  userName: zod.string(),
  userAvatarUrl: zod.string().nullish(),
  type: zod.enum(["buy", "sell"]),
  asset: zod.string(),
  amount: zod.number(),
  price: zod.number(),
  currency: zod.string(),
  minOrder: zod.number(),
  maxOrder: zod.number(),
  paymentMethods: zod.array(zod.string()),
  completionRate: zod.number(),
  totalTrades: zod.number(),
  status: zod.enum(["active", "inactive", "completed"]),
  createdAt: zod.string(),
});
export const GetP2PListingsResponse = zod.array(GetP2PListingsResponseItem);

/**
 * @summary Create a new P2P listing
 */
export const CreateP2PListingBody = zod.object({
  type: zod.enum(["buy", "sell"]),
  asset: zod.string(),
  amount: zod.number(),
  price: zod.number(),
  currency: zod.string(),
  minOrder: zod.number(),
  maxOrder: zod.number(),
  paymentMethods: zod.array(zod.string()),
});

export const CreateP2PListingResponse = zod.object({
  id: zod.string(),
  userId: zod.string(),
  userName: zod.string(),
  userAvatarUrl: zod.string().nullish(),
  type: zod.enum(["buy", "sell"]),
  asset: zod.string(),
  amount: zod.number(),
  price: zod.number(),
  currency: zod.string(),
  minOrder: zod.number(),
  maxOrder: zod.number(),
  paymentMethods: zod.array(zod.string()),
  completionRate: zod.number(),
  totalTrades: zod.number(),
  status: zod.enum(["active", "inactive", "completed"]),
  createdAt: zod.string(),
});

/**
 * @summary Get user's P2P orders
 */
export const GetP2POrdersResponseItem = zod.object({
  id: zod.string(),
  listingId: zod.string(),
  buyerId: zod.string(),
  sellerId: zod.string(),
  asset: zod.string(),
  amount: zod.number(),
  price: zod.number(),
  currency: zod.string(),
  status: zod.enum([
    "pending",
    "payment_sent",
    "completed",
    "disputed",
    "cancelled",
  ]),
  createdAt: zod.string(),
});
export const GetP2POrdersResponse = zod.array(GetP2POrdersResponseItem);

/**
 * @summary Create a P2P order (initiate trade)
 */
export const CreateP2POrderBody = zod.object({
  listingId: zod.string(),
  amount: zod.number(),
});

export const CreateP2POrderResponse = zod.object({
  id: zod.string(),
  listingId: zod.string(),
  buyerId: zod.string(),
  sellerId: zod.string(),
  asset: zod.string(),
  amount: zod.number(),
  price: zod.number(),
  currency: zod.string(),
  status: zod.enum([
    "pending",
    "payment_sent",
    "completed",
    "disputed",
    "cancelled",
  ]),
  createdAt: zod.string(),
});

/**
 * @summary Get P2P admin notifications
 */
export const GetP2PNotificationsResponseItem = zod.object({
  id: zod.string(),
  type: zod.enum([
    "deposit_incoming",
    "deposit_confirmed",
    "order_update",
    "admin_message",
  ]),
  title: zod.string(),
  message: zod.string(),
  orderId: zod.string().nullish(),
  read: zod.boolean(),
  createdAt: zod.string(),
});
export const GetP2PNotificationsResponse = zod.array(
  GetP2PNotificationsResponseItem,
);

/**
 * @summary Get available assets to purchase
 */
export const GetAssetCatalogResponseItem = zod.object({
  id: zod.string(),
  symbol: zod.string(),
  name: zod.string(),
  price: zod.number(),
  currency: zod.string(),
  change24h: zod.number(),
  logoUrl: zod.string().nullish(),
  available: zod.boolean(),
});
export const GetAssetCatalogResponse = zod.array(GetAssetCatalogResponseItem);

/**
 * @summary Purchase an asset
 */
export const PurchaseAssetBody = zod.object({
  assetId: zod.string(),
  amount: zod.number(),
  paymentMethod: zod.enum(["main_wallet", "card", "bank_transfer"]),
});

export const PurchaseAssetResponse = zod.object({
  success: zod.boolean(),
  transactionId: zod.string(),
  assetSymbol: zod.string(),
  amountPurchased: zod.number(),
  totalCost: zod.number(),
  message: zod.string(),
});

/**
 * @summary Get user support tickets
 */
export const GetSupportTicketsResponseItem = zod.object({
  id: zod.string(),
  subject: zod.string(),
  status: zod.enum(["open", "in_progress", "resolved", "closed"]),
  priority: zod.enum(["low", "medium", "high", "urgent"]),
  messages: zod.array(
    zod.object({
      id: zod.string(),
      senderId: zod.string(),
      senderName: zod.string(),
      senderAvatar: zod.string().nullish(),
      content: zod.string(),
      context: zod.enum(["manager", "p2p", "support"]),
      contextId: zod.string().nullish(),
      isFromUser: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const GetSupportTicketsResponse = zod.array(
  GetSupportTicketsResponseItem,
);

/**
 * @summary Create a support ticket
 */
export const CreateSupportTicketBody = zod.object({
  subject: zod.string(),
  message: zod.string(),
  priority: zod.enum(["low", "medium", "high", "urgent"]),
});

export const CreateSupportTicketResponse = zod.object({
  id: zod.string(),
  subject: zod.string(),
  status: zod.enum(["open", "in_progress", "resolved", "closed"]),
  priority: zod.enum(["low", "medium", "high", "urgent"]),
  messages: zod.array(
    zod.object({
      id: zod.string(),
      senderId: zod.string(),
      senderName: zod.string(),
      senderAvatar: zod.string().nullish(),
      content: zod.string(),
      context: zod.enum(["manager", "p2p", "support"]),
      contextId: zod.string().nullish(),
      isFromUser: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
