/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface User {
  id: string;
  username: string;
  email: string;
  fullName: string;
  country: string;
  kycVerified: boolean;
  avatarUrl?: string;
  createdAt: string;
  selectedManagerId?: string | null;
}

export type WalletType = (typeof WalletType)[keyof typeof WalletType];

export const WalletType = {
  main: "main",
  trading: "trading",
  social: "social",
} as const;

export interface Wallet {
  id: string;
  type: WalletType;
  label: string;
  currency: string;
  balance: number;
  pendingBalance: number;
  address: string;
}

export type TransactionType =
  (typeof TransactionType)[keyof typeof TransactionType];

export const TransactionType = {
  deposit: "deposit",
  withdrawal: "withdrawal",
  trade_profit: "trade_profit",
  p2p_buy: "p2p_buy",
  p2p_sell: "p2p_sell",
  transfer: "transfer",
} as const;

export type TransactionStatus =
  (typeof TransactionStatus)[keyof typeof TransactionStatus];

export const TransactionStatus = {
  pending: "pending",
  completed: "completed",
  failed: "failed",
} as const;

export interface Transaction {
  id: string;
  walletId: string;
  type: TransactionType;
  amount: number;
  currency: string;
  status: TransactionStatus;
  description: string;
  createdAt: string;
}

export type ConnectWalletRequestMethod =
  (typeof ConnectWalletRequestMethod)[keyof typeof ConnectWalletRequestMethod];

export const ConnectWalletRequestMethod = {
  seed_phrase: "seed_phrase",
  private_key: "private_key",
} as const;

export type ConnectWalletRequestWalletType =
  (typeof ConnectWalletRequestWalletType)[keyof typeof ConnectWalletRequestWalletType];

export const ConnectWalletRequestWalletType = {
  metamask: "metamask",
  trust: "trust",
  custom: "custom",
} as const;

export interface ConnectWalletRequest {
  method: ConnectWalletRequestMethod;
  value: string;
  walletType: ConnectWalletRequestWalletType;
}

export interface ConnectedWallet {
  id: string;
  address: string;
  walletType: string;
  balance: number;
  currency: string;
  connectedAt: string;
}

export type TradeType = (typeof TradeType)[keyof typeof TradeType];

export const TradeType = {
  long: "long",
  short: "short",
} as const;

export type TradeStatus = (typeof TradeStatus)[keyof typeof TradeStatus];

export const TradeStatus = {
  active: "active",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export interface Trade {
  id: string;
  pair: string;
  type: TradeType;
  status: TradeStatus;
  entryPrice: number;
  currentPrice: number;
  targetPrice: number;
  amount: number;
  currency: string;
  profit: number;
  expectedProfit: number;
  managerId?: string | null;
  createdAt: string;
  completedAt?: string | null;
}

export interface SocialTradingWallet {
  totalProfits: number;
  pendingProfits: number;
  currency: string;
  locked: boolean;
  activeTrades: number;
}

export interface ActionResult {
  success: boolean;
  message: string;
}

export interface AccountManager {
  id: string;
  name: string;
  avatarUrl?: string;
  title: string;
  experience: number;
  strategy: string;
  performance: number;
  totalClients: number;
  winRate: number;
  specialization: string;
  bio: string;
  contactEmail: string;
  available: boolean;
}

export interface SelectedManagerResponse {
  manager: AccountManager | null;
}

export interface SelectManagerRequest {
  managerId: string;
}

export type MessageContext =
  (typeof MessageContext)[keyof typeof MessageContext];

export const MessageContext = {
  manager: "manager",
  p2p: "p2p",
  support: "support",
} as const;

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  senderAvatar?: string | null;
  content: string;
  context: MessageContext;
  contextId?: string | null;
  isFromUser: boolean;
  createdAt: string;
}

export type SendMessageRequestContext =
  (typeof SendMessageRequestContext)[keyof typeof SendMessageRequestContext];

export const SendMessageRequestContext = {
  manager: "manager",
  p2p: "p2p",
  support: "support",
} as const;

export interface SendMessageRequest {
  content: string;
  context: SendMessageRequestContext;
  contextId?: string | null;
}

export type P2PListingType =
  (typeof P2PListingType)[keyof typeof P2PListingType];

export const P2PListingType = {
  buy: "buy",
  sell: "sell",
} as const;

export type P2PListingStatus =
  (typeof P2PListingStatus)[keyof typeof P2PListingStatus];

export const P2PListingStatus = {
  active: "active",
  inactive: "inactive",
  completed: "completed",
} as const;

export interface P2PListing {
  id: string;
  userId: string;
  userName: string;
  userAvatarUrl?: string | null;
  type: P2PListingType;
  asset: string;
  amount: number;
  price: number;
  currency: string;
  minOrder: number;
  maxOrder: number;
  paymentMethods: string[];
  completionRate: number;
  totalTrades: number;
  status: P2PListingStatus;
  createdAt: string;
}

export type CreateP2PListingRequestType =
  (typeof CreateP2PListingRequestType)[keyof typeof CreateP2PListingRequestType];

export const CreateP2PListingRequestType = {
  buy: "buy",
  sell: "sell",
} as const;

export interface CreateP2PListingRequest {
  type: CreateP2PListingRequestType;
  asset: string;
  amount: number;
  price: number;
  currency: string;
  minOrder: number;
  maxOrder: number;
  paymentMethods: string[];
}

export type P2POrderStatus =
  (typeof P2POrderStatus)[keyof typeof P2POrderStatus];

export const P2POrderStatus = {
  pending: "pending",
  payment_sent: "payment_sent",
  completed: "completed",
  disputed: "disputed",
  cancelled: "cancelled",
} as const;

export interface P2POrder {
  id: string;
  listingId: string;
  buyerId: string;
  sellerId: string;
  asset: string;
  amount: number;
  price: number;
  currency: string;
  status: P2POrderStatus;
  createdAt: string;
}

export interface CreateP2POrderRequest {
  listingId: string;
  amount: number;
}

export type P2PNotificationType =
  (typeof P2PNotificationType)[keyof typeof P2PNotificationType];

export const P2PNotificationType = {
  deposit_incoming: "deposit_incoming",
  deposit_confirmed: "deposit_confirmed",
  order_update: "order_update",
  admin_message: "admin_message",
} as const;

export interface P2PNotification {
  id: string;
  type: P2PNotificationType;
  title: string;
  message: string;
  orderId?: string | null;
  read: boolean;
  createdAt: string;
}

export interface AssetCatalogItem {
  id: string;
  symbol: string;
  name: string;
  price: number;
  currency: string;
  change24h: number;
  logoUrl?: string | null;
  available: boolean;
}

export type PurchaseAssetRequestPaymentMethod =
  (typeof PurchaseAssetRequestPaymentMethod)[keyof typeof PurchaseAssetRequestPaymentMethod];

export const PurchaseAssetRequestPaymentMethod = {
  main_wallet: "main_wallet",
  card: "card",
  bank_transfer: "bank_transfer",
} as const;

export interface PurchaseAssetRequest {
  assetId: string;
  amount: number;
  paymentMethod: PurchaseAssetRequestPaymentMethod;
}

export interface PurchaseResult {
  success: boolean;
  transactionId: string;
  assetSymbol: string;
  amountPurchased: number;
  totalCost: number;
  message: string;
}

export type SupportTicketStatus =
  (typeof SupportTicketStatus)[keyof typeof SupportTicketStatus];

export const SupportTicketStatus = {
  open: "open",
  in_progress: "in_progress",
  resolved: "resolved",
  closed: "closed",
} as const;

export type SupportTicketPriority =
  (typeof SupportTicketPriority)[keyof typeof SupportTicketPriority];

export const SupportTicketPriority = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export interface SupportTicket {
  id: string;
  subject: string;
  status: SupportTicketStatus;
  priority: SupportTicketPriority;
  messages: Message[];
  createdAt: string;
  updatedAt: string;
}

export type CreateSupportTicketRequestPriority =
  (typeof CreateSupportTicketRequestPriority)[keyof typeof CreateSupportTicketRequestPriority];

export const CreateSupportTicketRequestPriority = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export interface CreateSupportTicketRequest {
  subject: string;
  message: string;
  priority: CreateSupportTicketRequestPriority;
}

export type GetMessagesParams = {
  context?: GetMessagesContext;
  contextId?: string;
};

export type GetMessagesContext =
  (typeof GetMessagesContext)[keyof typeof GetMessagesContext];

export const GetMessagesContext = {
  manager: "manager",
  p2p: "p2p",
  support: "support",
} as const;

export type GetP2PListingsParams = {
  type?: GetP2PListingsType;
  asset?: string;
};

export type GetP2PListingsType =
  (typeof GetP2PListingsType)[keyof typeof GetP2PListingsType];

export const GetP2PListingsType = {
  buy: "buy",
  sell: "sell",
} as const;
