/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ConnectWalletRequestWalletType =
  (typeof ConnectWalletRequestWalletType)[keyof typeof ConnectWalletRequestWalletType];

export const ConnectWalletRequestWalletType = {
  metamask: "metamask",
  trust: "trust",
  custom: "custom",
} as const;
