/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectWalletRequestMethod } from "./connectWalletRequestMethod";
import type { ConnectWalletRequestWalletType } from "./connectWalletRequestWalletType";

export interface ConnectWalletRequest {
  method: ConnectWalletRequestMethod;
  value: string;
  walletType: ConnectWalletRequestWalletType;
}
