/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateP2PListingRequestType } from "./createP2PListingRequestType";

export interface CreateP2PListingRequest {
  type: CreateP2PListingRequestType;
  asset: string;
  amount: number;
  price: number;
  currency: string;
  minOrder: number;
  maxOrder: number;
  paymentMethods: string[];
}
