/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export type CreateSupportTicketRequestPriority =
  (typeof CreateSupportTicketRequestPriority)[keyof typeof CreateSupportTicketRequestPriority];

export const CreateSupportTicketRequestPriority = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;
