/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { P2PNotificationType } from "./p2PNotificationType";

export interface P2PNotification {
  id: string;
  type: P2PNotificationType;
  title: string;
  message: string;
  orderId?: string | null;
  read: boolean;
  createdAt: string;
}
