/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export type P2PNotificationType =
  (typeof P2PNotificationType)[keyof typeof P2PNotificationType];

export const P2PNotificationType = {
  deposit_incoming: "deposit_incoming",
  deposit_confirmed: "deposit_confirmed",
  order_update: "order_update",
  admin_message: "admin_message",
} as const;
