/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export type SendMessageRequestContext =
  (typeof SendMessageRequestContext)[keyof typeof SendMessageRequestContext];

export const SendMessageRequestContext = {
  manager: "manager",
  p2p: "p2p",
  support: "support",
} as const;
