/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { SendMessageRequestContext } from "./sendMessageRequestContext";

export interface SendMessageRequest {
  content: string;
  context: SendMessageRequestContext;
  contextId?: string | null;
}
