/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export type TransactionType =
  (typeof TransactionType)[keyof typeof TransactionType];

export const TransactionType = {
  deposit: "deposit",
  withdrawal: "withdrawal",
  trade_profit: "trade_profit",
  p2p_buy: "p2p_buy",
  p2p_sell: "p2p_sell",
  transfer: "transfer",
} as const;
