/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  id: string;
  username: string;
  email: string;
  fullName: string;
  country: string;
  kycVerified: boolean;
  avatarUrl?: string;
  createdAt: string;
  selectedManagerId?: string | null;
}
