/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NeXTrade Platform API
 * OpenAPI spec version: 0.1.0
 */

export type WalletType = (typeof WalletType)[keyof typeof WalletType];

export const WalletType = {
  main: "main",
  trading: "trading",
  social: "social",
} as const;
